---
title: "Env-Chem_Gen-Code"
author: "J.Behrens"
date: "11/30/2020"
output: html_document
---

# Set-Up R Environment
```{r setup}
## Clear environment
rm(list = ls())

## Libraries
library(dataRetrieval)
library(tidyverse)
library(openxlsx)
library(leaflet)                                           
library(reshape2)
library(knitr)

#Set working directory
opts_knit$set(root.dir = "C:/Users/jbehr/OneDrive - Duke University/Documents/5. R/General_Env_Chem")

```

# Download Data

For now, just looking at organic contaminants on the USGS PCode List (NWIS).

```{r}
# Import Raw Data
USGS_Param<-read.csv("raw_data/RAW_USGS-Param-Codes.csv") %>% 
  mutate(casrn = str_replace_all(casrn, "-","")) 

Lists_CompTox_raw<-read.csv("raw_data/CompToxChemicalsDashboard-Batch-Search_2020-11-30.csv")

Chem_CompTox_raw<-read.csv("raw_data/RAW_CompToxChemicalsDashboard-All-USGS-PCs.csv") %>% 
  mutate(CASRN = str_replace_all(CASRN, "-",""))

TSCA_List<-read.csv("raw_data/TSCAINV_062020.csv") %>% 
  filter(ACTIVITY == "ACTIVE") %>% 
  distinct(casregno, .keep_all = TRUE)
List_Names_CompTox<-read.csv("raw_data/CompTox_Lists.csv")

# Make a few simiple datsets
All_CompTox_Data<-left_join(Lists_CompTox_raw, Chem_CompTox_raw, by="DTXSID") %>% 
  filter(DTXSID !="-")

Lists_CompTox<- Lists_CompTox_raw %>% 
  gather(LISTS, Yes_or_No, 6:293) %>% 
  filter(Yes_or_No == "Y") %>% 
  select(!Yes_or_No) %>% #These three lines consolidates the lists, and removes categories the cmpd is not in
  arrange(-desc(PREFERRED_NAME)) %>% 
  left_join(List_Names_CompTox)

```

# Merge Datasets
```{r}
# Count of compounds, by list
Lists_CompTox %>% 
  group_by(LISTS) %>%   
  count() %>%
  full_join(List_Names_CompTox) %>% 
  arrange(desc(n))

# Count of compounds, by category
Categories<-Lists_CompTox %>%
  filter(Gen_Type == "Category") %>%
  distinct(PREFERRED_NAME, Specific_Type, .keep_all = TRUE)

Categories %>% 
  group_by(Specific_Type) %>% 
  count() %>% 
  arrange(desc(n))

USGS_Param %>% 
  group_by(parameter_group_nm) %>% 
  count() %>% 
  arrange(desc(n))

# Categories for Elements
Lists_CompTox_raw %>%
  filter(ELEMENTS == "Y") %>% 

  filter(Yes_or_No == "Y") %>%   gather(LISTS, Yes_or_No, 6:293) %>% 
  select(!Yes_or_No) %>% #These three lines consolidates the lists, and removes categories the cmpd is not in
  left_join(List_Names_CompTox) %>% 
  filter(Gen_Type == "Category") %>%
  distinct(PREFERRED_NAME, Specific_Type, .keep_all = TRUE) %>% 
  group_by(Specific_Type) %>% 
  count() %>% 
  arrange(desc(n))

```

#Some simple stats
```{r}

#Categories for each chemical
Chemical_By_Cat<- Lists_CompTox %>%
  select(PREFERRED_NAME, DTXSID, Specific_Type) %>% 
  unique() %>% 
  pivot_wider(names_from = Specific_Type, values_from = Specific_Type) %>% 
  unite(Other:Fertilizer, col="Categories_Merged", sep=";") %>% 
  mutate(Categories_Merged = str_remove_all(Categories_Merged, "NA;|NA"))

# All the PFAS Chemicals
full_PFAS<-Categories %>% 
  filter(Specific_Type == "PFAS")

```

# Specifically looking at Muddy Creek Pharmacueticals
```{r}
# Import Raw Data
## already imported Lists_Names_Comptox, USGS_Param, and TSCA_List in teh above code
List_Names_CompTox<-read.csv("raw_data/CompTox_Lists.csv")

MC_Lists_CompTox_raw<-read.csv("raw_data/MC_CompToxChemicalsDashboard-Batch-Search_2020-12-03_13-03-07.csv")

MC_Chem_CompTox_raw<-read.csv("raw_data/MC_CompToxChemicalsDashboard-Batch-Search_2020-12-03_13-04-39.csv") %>% 
  mutate(CASRN = str_replace_all(CASRN, "-",""))

# Make a few simiple datsets
MC_All_CompTox_Data<-left_join(MC_Lists_CompTox_raw, MC_Chem_CompTox_raw, by="DTXSID") %>% 
  filter(DTXSID !="-")

MC_Lists_CompTox<- MC_Lists_CompTox_raw %>% 
  gather(LISTS, Yes_or_No, 6:292) %>% 
  filter(Yes_or_No == "Y") %>% 
  select(!Yes_or_No) %>% #These three lines consolidates the lists, and removes categories the cmpd is not in
  arrange(-desc(PREFERRED_NAME)) %>% 
  left_join(List_Names_CompTox)


# Simple Tables

# Count of compounds, by list
MC_Lists_CompTox %>% 
  group_by(LISTS) %>%   
  count() %>%
  full_join(List_Names_CompTox) %>% 
  arrange(desc(n))

# Categories
MC_Lists_CompTox_raw %>%
  gather(LISTS, Yes_or_No, 6:292) %>% 
  filter(Yes_or_No == "Y") %>% 
  select(!Yes_or_No) %>% #These three lines consolidates the lists, and removes categories the cmpd is not in
  left_join(List_Names_CompTox) %>% 
  filter(Gen_Type == "Category") %>%
  distinct(PREFERRED_NAME, Specific_Type, .keep_all = TRUE) %>% 
  group_by(Specific_Type) %>% 
  count() %>% 
  arrange(desc(n))


#Categories for each chemical
MC_Chemical_By_Cat<- MC_Lists_CompTox %>%
  select(PREFERRED_NAME, DTXSID, Specific_Type) %>% 
  unique() %>% 
  pivot_wider(names_from = Specific_Type, values_from = Specific_Type) %>% 
  unite(Other:Rubber, col="Categories_Merged", sep=";") %>% #Make sure column names are all
  mutate(Categories_Merged = str_remove_all(Categories_Merged, "NA;|NA"))


```

# Chemistry figures of Muddy Creek Pharma

```{r}
MC_Chem_CompTox_raw$OCTANOL_AIR_PARTITION_COEFF_LOGKOA_OPERA_PRED<-as.numeric(as.character(
  MC_Chem_CompTox_raw$OCTANOL_AIR_PARTITION_COEFF_LOGKOA_OPERA_PRED))
MC_Chem_CompTox_raw$OCTANOL_WATER_PARTITION_LOGP_OPERA_PRED <-as.numeric(as.character(
  MC_Chem_CompTox_raw$OCTANOL_WATER_PARTITION_LOGP_OPERA_PRED))
MC_Chem_CompTox_raw$BIOCONCENTRATION_FACTOR_TEST_PRED <-as.numeric(as.character(
  MC_Chem_CompTox_raw$BIOCONCENTRATION_FACTOR_TEST_PRED))
MC_Chem_CompTox_raw$BIOCONCENTRATION_FACTOR_OPERA_PRED <-as.numeric(as.character(
  MC_Chem_CompTox_raw$BIOCONCENTRATION_FACTOR_OPERA_PRED))

MC_KOA_vs_KOW<-MC_Chem_CompTox_raw  %>% 
  filter(DTXSID !="-") %>% 
  ggplot(aes(x=OCTANOL_WATER_PARTITION_LOGP_OPERA_PRED,
             y=OCTANOL_AIR_PARTITION_COEFF_LOGKOA_OPERA_PRED,
             color=OCTANOL_WATER_PARTITION_LOGP_OPERA_PRED)) +
  geom_point() +
  theme_classic() +  
  labs(title="LogKOA vs. LogKOW")+
  ylab("LogKoa")+ xlab("LogKow") +
  scale_color_gradient2(low="red", mid = "grey", high= "blue", midpoint = 5) # Canada & EU LogKOW for bioaccum
print(MC_KOA_vs_KOW)

MC_BCF<-MC_Chem_CompTox_raw %>% 
  filter(DTXSID !="-") %>% 
  ggplot(aes(x=log10(BIOCONCENTRATION_FACTOR_TEST_PRED),
             y=log10(BIOCONCENTRATION_FACTOR_OPERA_PRED),
             color = log10(BIOCONCENTRATION_FACTOR_OPERA_PRED))) +
  geom_point() +
  scale_color_gradient2(low="red", mid = "grey", high= "blue", midpoint = 3.699) + #log10(5000) ~ 3.699; US limit for bioaccum
  theme_classic() +  
  labs(title="Bioconcentration Factor (Predicted by two models)")+
  ylab("Log(BCF OPERA Model)")+ xlab("Log(BCF Predicted)")
print(MC_BCF)  
```

# Same but for all USGS Parameters

```{r}
Chem_CompTox_raw$OCTANOL_AIR_PARTITION_COEFF_LOGKOA_OPERA_PRED<-as.numeric(as.character(
  Chem_CompTox_raw$OCTANOL_AIR_PARTITION_COEFF_LOGKOA_OPERA_PRED))
Chem_CompTox_raw$OCTANOL_WATER_PARTITION_LOGP_OPERA_PRED <-as.numeric(as.character(
  Chem_CompTox_raw$OCTANOL_WATER_PARTITION_LOGP_OPERA_PRED))
Chem_CompTox_raw$BIOCONCENTRATION_FACTOR_TEST_PRED <-as.numeric(as.character(
  Chem_CompTox_raw$BIOCONCENTRATION_FACTOR_TEST_PRED))
Chem_CompTox_raw$BIOCONCENTRATION_FACTOR_OPERA_PRED <-as.numeric(as.character(
  Chem_CompTox_raw$BIOCONCENTRATION_FACTOR_OPERA_PRED))

KOA_vs_KOW<-Chem_CompTox_raw  %>% 
  filter(DTXSID !="-") %>% 
  ggplot(aes(x=OCTANOL_WATER_PARTITION_LOGP_OPERA_PRED,
             y=OCTANOL_AIR_PARTITION_COEFF_LOGKOA_OPERA_PRED,
             color=OCTANOL_WATER_PARTITION_LOGP_OPERA_PRED)) +
  geom_point() +
  theme_classic() +  
  labs(title="LogKOA vs. LogKOW")+
  ylab("LogKoa")+ xlab("LogKow")+
  scale_color_gradient2(low="red", mid = "grey", high= "blue", midpoint = 5) # Canada & EU LogKOW for bioaccum
print(KOA_vs_KOW)

BCF<-Chem_CompTox_raw %>% 
  filter(DTXSID !="-") %>% 
  ggplot(aes(x=log10(BIOCONCENTRATION_FACTOR_TEST_PRED),
             y=log10(BIOCONCENTRATION_FACTOR_OPERA_PRED),
             color = log10(BIOCONCENTRATION_FACTOR_OPERA_PRED))) +
  geom_point() +
  scale_color_gradient2(low="red", mid = "grey", high= "blue", midpoint = 3.699) + #log10(5000) ~ 3.699; US limit for bioaccum
  theme_classic() +  
  labs(title="Bioconcentration Factor (Predicted by two models)")+
  ylab("Log(BCF OPERA Model)")+ xlab("Log(BCF Predicted)")
print(BCF)  
```



# Plot: By Decade

```{r}

#OLD CODE

Year_Plot<- Both_Water %>% 
  ggplot(aes(x=as.character(Decade), fill=Site_Group)) +
  geom_bar() +
  theme_classic() + 
  theme(axis.text.x = element_text(angle=45, hjust = 1)) + 
  labs(title="Both Areas by Decade")
print(Year_Plot)
##ggsave("output/Years.png")

Year_4_site_Plot<- Both_Water  %>% 
  filter(str_detect(MonitoringLocationIdentifier, 
                    "USGS-02085500|USGS-02086500|USGS-02086849|J1269000")) %>% 
  ggplot(aes(x=as.character(Decade), fill=MonitoringLocationName)) +
  geom_bar() +
  theme_classic() + 
  theme(axis.text.x = element_text(angle=45, hjust = 1)) + 
  labs(title="Both Areas by Decade")
print(Year_4_site_Plot)
##ggsave("output/Years_4_sites.png")

decade_EC_Plot<-Ellerbe_Creek_Water %>% 
  ggplot(aes(x=MonitoringLocationIdentifier, fill = as.character(Decade))) +
  geom_bar() +
  theme_classic() + 
  theme(axis.text.x = element_text(angle=45, hjust = 1)) + 
  labs(title="Ellerbe Creek by Decade")
print(decade_EC_Plot)
##ggsave("output/Decades_EC.png")

decade_FR_Plot<-Flat_River_Water %>% 
  ggplot(aes(x=MonitoringLocationIdentifier, fill = as.character(Decade))) +
  geom_bar() +
  theme_classic() + 
  theme(axis.text.x = element_text(angle=45, hjust = 1)) + 
  labs(title="Flat River by Decade")
print(decade_FR_Plot)
##ggsave("output/Decades_FR.png")
```